// 导入阿里云翻译
import { translateWithAliyun, AliyunConfig } from './aliyunTranslate';

// 翻译服务配置
export const TRANSLATION_CONFIG = {
  // 优先使用的翻译服务: 'google' | 'mymemory' | 'aliyun' | 'mock'
  preferredService: 'aliyun' as 'google' | 'mymemory' | 'aliyun' | 'mock',
  // 是否启用 Google 翻译
  enableGoogleTranslate: false,
};

export async function translateWithGoogle(text: string, targetLang: string, sourceLang = 'en'): Promise<string> {
  console.log('[Google Translate] 翻译到', targetLang);
  
  try {
    // 使用免费的 Google 翻译 API（通过第三方服务）
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=${sourceLang}&tl=${targetLang}&dt=t&q=${encodeURIComponent(text)}`;
    const response = await fetch(url);
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    
    const data = await response.json();
    
    if (data && data[0] && Array.isArray(data[0])) {
      const translatedText = data[0].map((item: any) => item[0]).join('');
      console.log(`[Google Translate] "${text}" -> "${translatedText}"`);
      return translatedText;
    } else {
      throw new Error('Invalid response from Google Translate');
    }
  } catch (error) {
    console.error('[Google Translate] 错误:', error);
    throw error;
  }
}

export async function translateWithMyMemory(text: string, targetLang: string, sourceLang = 'en'): Promise<string> {
  console.log('[MyMemory Translate] 翻译到', targetLang);
  
  try {
    // 如果是自动检测，我们不传源语言或者用 'en' 作为默认
    const actualSourceLang = sourceLang === 'auto' ? 'en' : sourceLang;
    const langPair = `${actualSourceLang}|${targetLang}`;
    const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${langPair}`;
    const response = await fetch(url);
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    
    const data = await response.json();
    
    if (data.responseStatus === 200 && data.responseData) {
      console.log(`[MyMemory] "${text}" -> "${data.responseData.translatedText}"`);
      return data.responseData.translatedText;
    } else {
      console.warn(`[MyMemory] 翻译失败:`, data.responseDetails);
      return text;
    }
  } catch (error) {
    console.error('[MyMemory Translate] 错误:', error);
    throw error;
  }
}

export async function translateBatchWithAPI(texts: string[], targetLang: string, sourceLang = 'en'): Promise<Record<string, string>> {
  console.log('[API Translate] 翻译', texts.length, '条文本到', targetLang);
  
  const results: Record<string, string> = {};
  
  // 阿里云翻译配置
  const aliyunConfig: AliyunConfig = {
    accessKeyId: import.meta.env.VITE_ALIYUN_ACCESS_KEY_ID || '',
    accessKeySecret: import.meta.env.VITE_ALIYUN_ACCESS_KEY_SECRET || '',
    region: import.meta.env.VITE_ALIYUN_REGION || 'cn-hangzhou',
  };
  
  for (const text of texts) {
    let result: string;
    let serviceUsed = '';
    
    try {
      if (TRANSLATION_CONFIG.preferredService === 'aliyun' && aliyunConfig.accessKeyId && aliyunConfig.accessKeySecret) {
        try {
          // 转换语言代码
          const sourceLangCode = sourceLang === 'auto' ? 'auto' : sourceLang;
          const targetLangCode = targetLang;
          
          result = await translateWithAliyun(text, sourceLangCode, targetLangCode, aliyunConfig);
          serviceUsed = '阿里云';
        } catch (e) {
          console.log('[API] 阿里云翻译失败，尝试MyMemory');
          result = await translateWithMyMemory(text, targetLang, sourceLang);
          serviceUsed = 'MyMemory';
        }
      } else if (TRANSLATION_CONFIG.preferredService === 'google' && TRANSLATION_CONFIG.enableGoogleTranslate) {
        try {
          result = await translateWithGoogle(text, targetLang, sourceLang);
          serviceUsed = 'Google';
        } catch (e) {
          console.log('[API] Google翻译失败，尝试MyMemory');
          result = await translateWithMyMemory(text, targetLang, sourceLang);
          serviceUsed = 'MyMemory';
        }
      } else if (TRANSLATION_CONFIG.preferredService === 'mymemory') {
        try {
          result = await translateWithMyMemory(text, targetLang, sourceLang);
          serviceUsed = 'MyMemory';
        } catch (e) {
          console.log('[API] MyMemory失败，使用模拟翻译');
          result = mockTranslateSingle(text, targetLang);
          serviceUsed = 'Mock';
        }
      } else {
        result = mockTranslateSingle(text, targetLang);
        serviceUsed = 'Mock';
      }
      
      console.log(`[API] 使用 ${serviceUsed} 翻译: "${text}" -> "${result}"`);
    } catch (error) {
      console.error(`[API] 翻译失败 "${text}":`, error);
      result = mockTranslateSingle(text, targetLang);
    }
    results[text] = result;
  }
  
  console.log('[API Translate] 翻译完成');
  return results;
}

function mockTranslateSingle(text: string, targetLang: string): string {
  // 常用中文短语的翻译库
  const mockTranslations: Record<string, Record<string, string>> = {
    'zh-CN': {
      'Welcome': '欢迎',
      'Welcome to': '欢迎来到',
      'IB Portal': 'IB 门户',
      'Manage your investments with ease': '轻松管理您的投资',
      'Get Started': '开始使用',
      'Why Choose Us': '为什么选择我们',
      'Real-time Updates': '实时更新',
      '首页': '首页',
      '关于我们': '关于我们',
      '联系我们': '联系我们',
      '搜索...': '搜索...',
      '个人中心': '个人中心',
      'Secure Platform': '安全平台',
      '© 2024 All Rights Reserved': '© 2024 保留所有权利',
      '登录': '登录',
      '注册': '注册',
      '密码': '密码',
      '邮箱': '邮箱',
      '设置': '设置',
      '退出': '退出',
      '确认': '确认',
      '取消': '取消',
      '保存': '保存',
      '删除': '删除',
      '编辑': '编辑',
      '提交': '提交',
      '返回': '返回',
      '下一步': '下一步',
      '上一步': '上一步',
      '加载中...': '加载中...',
      '加载失败': '加载失败',
      '重试': '重试',
    },
    'zh-TW': {
      'Welcome': '歡迎',
      'Welcome to': '歡迎來到',
      'IB Portal': 'IB 門戶',
      'Manage your investments with ease': '輕鬆管理您的投資',
      'Get Started': '開始使用',
      'Why Choose Us': '為什麼選擇我們',
      'Real-time Updates': '實時更新',
      '首页': '首頁',
      '关于我们': '關於我們',
      '联系我们': '聯繫我們',
      '搜索...': '搜尋...',
      '个人中心': '個人中心',
      'Secure Platform': '安全平台',
      '© 2024 All Rights Reserved': '© 2024 保留所有權利',
    },
    'en': {
      '欢迎': 'Welcome',
      '欢迎来到': 'Welcome to',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Manage your investments with ease',
      '开始使用': 'Get Started',
      '为什么选择我们': 'Why Choose Us',
      '实时更新': 'Real-time Updates',
      '首页': 'Home',
      '关于我们': 'About Us',
      '联系我们': 'Contact Us',
      '搜索...': 'Search...',
      '个人中心': 'Profile',
      '安全平台': 'Secure Platform',
      '© 2024 保留所有权利': '© 2024 All Rights Reserved',
      '登录': 'Login',
      '注册': 'Register',
      '密码': 'Password',
      '邮箱': 'Email',
      '设置': 'Settings',
      '退出': 'Logout',
      '确认': 'Confirm',
      '取消': 'Cancel',
      '保存': 'Save',
      '删除': 'Delete',
      '编辑': 'Edit',
      '提交': 'Submit',
      '返回': 'Back',
      '下一步': 'Next',
      '上一步': 'Previous',
      '加载中...': 'Loading...',
      '加载失败': 'Loading failed',
      '重试': 'Retry',
    },
    'ja': {
      '欢迎': 'ようこそ',
      '欢迎来到': 'へようこそ',
      'IB 门户': 'IB ポータル',
      '轻松管理您的投资': '投資を簡単に管理',
      '开始使用': '始める',
      '为什么选择我们': 'なぜ私たちを選ぶのか',
      '实时更新': 'リアルタイム更新',
      '首页': 'ホーム',
      '关于我们': '私たちについて',
      '联系我们': 'お問い合わせ',
      '搜索...': '検索...',
      '个人中心': 'プロフィール',
      '安全平台': '安全なプラットフォーム',
      '登录': 'ログイン',
      '注册': '登録',
      '密码': 'パスワード',
      '邮箱': 'メール',
      '设置': '設定',
      '退出': 'ログアウト',
      '确认': '確認',
      '取消': 'キャンセル',
      '保存': '保存',
      '删除': '削除',
      '编辑': '編集',
      '提交': '送信',
      '返回': '戻る',
      '下一步': '次へ',
      '上一步': '前へ',
    },
    'ko': {
      '欢迎': '환영',
      '欢迎来到': '에 오신 것을 환영합니다',
      'IB 门户': 'IB 포털',
      '轻松管理您的投资': '투자 관리 쉽게',
      '开始使用': '시작하기',
      '为什么选择我们': '왜 우리를 선택하는가',
      '实时更新': '실시간 업데이트',
      '首页': '홈',
      '关于我们': '회사 소개',
      '联系我们': '문의하기',
      '搜索...': '검색...',
      '个人中心': '프로필',
      '安全平台': '안전한 플랫폼',
      '登录': '로그인',
      '注册': '가입',
      '密码': '비밀번호',
      '邮箱': '이메일',
      '设置': '설정',
      '退出': '로그아웃',
      '确认': '확인',
      '取消': '취소',
      '保存': '저장',
      '删除': '삭제',
      '编辑': '편집',
      '提交': '제출',
      '返回': '뒤로',
      '下一步': '다음',
      '上一步': '이전',
    },
    'de': {
      '欢迎': 'Willkommen',
      '欢迎来到': 'Willkommen bei',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Verwalten Sie Ihre Investitionen leicht',
      '开始使用': 'Loslegen',
      '为什么选择我们': 'Warum uns wählen',
      '实时更新': 'Echtzeit-Updates',
      '首页': 'Startseite',
      '关于我们': 'Über uns',
      '联系我们': 'Kontakt',
      '搜索...': 'Suchen...',
      '个人中心': 'Profil',
      '安全平台': 'Sichere Plattform',
      '登录': 'Anmelden',
      '注册': 'Registrieren',
      '密码': 'Passwort',
      '邮箱': 'E-Mail',
      '设置': 'Einstellungen',
      '退出': 'Abmelden',
      '确认': 'Bestätigen',
      '取消': 'Abbrechen',
      '保存': 'Speichern',
      '删除': 'Löschen',
      '编辑': 'Bearbeiten',
      '提交': 'Absenden',
      '返回': 'Zurück',
      '下一步': 'Weiter',
      '上一步': 'Zurück',
    },
    'fr': {
      '欢迎': 'Bienvenue',
      '欢迎来到': 'Bienvenue sur',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Gérez vos investissements facilement',
      '开始使用': 'Commencer',
      '为什么选择我们': 'Pourquoi nous choisir',
      '实时更新': 'Mises à jour en temps réel',
      '首页': 'Accueil',
      '关于我们': 'À propos',
      '联系我们': 'Contact',
      '搜索...': 'Rechercher...',
      '个人中心': 'Profil',
      '安全平台': 'Plateforme sécurisée',
      '登录': 'Connexion',
      '注册': 'Inscription',
      '密码': 'Mot de passe',
      '邮箱': 'E-mail',
      '设置': 'Paramètres',
      '退出': 'Déconnexion',
      '确认': 'Confirmer',
      '取消': 'Annuler',
      '保存': 'Enregistrer',
      '删除': 'Supprimer',
      '编辑': 'Modifier',
      '提交': 'Soumettre',
      '返回': 'Retour',
      '下一步': 'Suivant',
      '上一步': 'Précédent',
    },
    'es': {
      '欢迎': 'Bienvenido',
      '欢迎来到': 'Bienvenido a',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Gestiona tus inversiones fácilmente',
      '开始使用': 'Empezar',
      '为什么选择我们': '¿Por qué elegirnos',
      '实时更新': 'Actualizaciones en tiempo real',
      '首页': 'Inicio',
      '关于我们': 'Sobre nosotros',
      '联系我们': 'Contacto',
      '搜索...': 'Buscar...',
      '个人中心': 'Perfil',
      '安全平台': 'Plataforma segura',
      '登录': 'Iniciar sesión',
      '注册': 'Registrarse',
      '密码': 'Contraseña',
      '邮箱': 'Correo electrónico',
      '设置': 'Configuración',
      '退出': 'Cerrar sesión',
      '确认': 'Confirmar',
      '取消': 'Cancelar',
      '保存': 'Guardar',
      '删除': 'Eliminar',
      '编辑': 'Editar',
      '提交': 'Enviar',
      '返回': 'Volver',
      '下一步': 'Siguiente',
      '上一步': 'Anterior',
    },
    'es-BR': {
      '欢迎': 'Bienvenido',
      '欢迎来到': 'Bienvenido a',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Gestiona tus inversiones fácilmente',
      '开始使用': 'Empezar',
      '为什么选择我们': '¿Por qué elegirnos',
      '实时更新': 'Actualizaciones en tiempo real',
      '首页': 'Inicio',
      '关于我们': 'Sobre nosotros',
      '联系我们': 'Contacto',
      '搜索...': 'Buscar...',
      '个人中心': 'Perfil',
      '安全平台': 'Plataforma segura',
      '登录': 'Iniciar sesión',
      '注册': 'Registrarse',
      '密码': 'Contraseña',
      '邮箱': 'Correo electrónico',
      '设置': 'Configuración',
      '退出': 'Cerrar sesión',
      '确认': 'Confirmar',
      '取消': 'Cancelar',
      '保存': 'Guardar',
      '删除': 'Eliminar',
      '编辑': 'Editar',
      '提交': 'Enviar',
      '返回': 'Volver',
      '下一步': 'Siguiente',
      '上一步': 'Anterior',
    },
    'pt': {
      '欢迎': 'Bem-vindo',
      '欢迎来到': 'Bem-vindo a',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Gerencie seus investimentos facilmente',
      '开始使用': 'Começar',
      '为什么选择我们': 'Por que nos escolher',
      '实时更新': 'Atualizações em tempo real',
      '首页': 'Início',
      '关于我们': 'Sobre nós',
      '联系我们': 'Contato',
      '搜索...': 'Pesquisar...',
      '个人中心': 'Perfil',
      '安全平台': 'Plataforma segura',
      '登录': 'Entrar',
      '注册': 'Registrar',
      '密码': 'Senha',
      '邮箱': 'E-mail',
      '设置': 'Configurações',
      '退出': 'Sair',
      '确认': 'Confirmar',
      '取消': 'Cancelar',
      '保存': 'Salvar',
      '删除': 'Excluir',
      '编辑': 'Editar',
      '提交': 'Enviar',
      '返回': 'Voltar',
      '下一步': 'Próximo',
      '上一步': 'Anterior',
    },
    'pt-BR': {
      '欢迎': 'Bem-vindo',
      '欢迎来到': 'Bem-vindo a',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Gerencie seus investimentos facilmente',
      '开始使用': 'Começar',
      '为什么选择我们': 'Por que nos escolher',
      '实时更新': 'Atualizações em tempo real',
      '首页': 'Início',
      '关于我们': 'Sobre nós',
      '联系我们': 'Contato',
      '搜索...': 'Pesquisar...',
      '个人中心': 'Perfil',
      '安全平台': 'Plataforma segura',
      '登录': 'Entrar',
      '注册': 'Registrar',
      '密码': 'Senha',
      '邮箱': 'E-mail',
      '设置': 'Configurações',
      '退出': 'Sair',
      '确认': 'Confirmar',
      '取消': 'Cancelar',
      '保存': 'Salvar',
      '删除': 'Excluir',
      '编辑': 'Editar',
      '提交': 'Enviar',
      '返回': 'Voltar',
      '下一步': 'Próximo',
      '上一步': 'Anterior',
    },
    'ru': {
      '欢迎': 'Добро пожаловать',
      '欢迎来到': 'Добро пожаловать в',
      'IB 门户': 'IB Портал',
      '轻松管理您的投资': 'Управляйте своими инвестициями легко',
      '开始使用': 'Начать',
      '为什么选择我们': 'Почему выбирают нас',
      '实时更新': 'Обновления в реальном времени',
      '首页': 'Главная',
      '关于我们': 'О нас',
      '联系我们': 'Связаться с нами',
      '搜索...': 'Поиск...',
      '个人中心': 'Профиль',
      '安全平台': 'Безопасная платформа',
      '登录': 'Войти',
      '注册': 'Регистрация',
      '密码': 'Пароль',
      '邮箱': 'Эл. почта',
      '设置': 'Настройки',
      '退出': 'Выйти',
      '确认': 'Подтвердить',
      '取消': 'Отмена',
      '保存': 'Сохранить',
      '删除': 'Удалить',
      '编辑': 'Редактировать',
      '提交': 'Отправить',
      '返回': 'Назад',
      '下一步': 'Далее',
      '上一步': 'Назад',
    },
    'th': {
      '欢迎': 'ยินดีต้อนรับ',
      '欢迎来到': 'ยินดีต้อนรับสู่',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'จัดการการลงทุนของคุณได้อย่างง่ายดาย',
      '开始使用': 'เริ่มต้นใช้งาน',
      '为什么选择我们': 'ทำไมต้องเลือกเรา',
      '实时更新': 'อัปเดตแบบเรียลไทม์',
      '首页': 'หน้าแรก',
      '关于我们': 'เกี่ยวกับเรา',
      '联系我们': 'ติดต่อเรา',
      '搜索...': 'ค้นหา...',
      '个人中心': 'โปรไฟล์',
      '安全平台': 'แพลตฟอร์มที่ปลอดภัย',
      '登录': 'เข้าสู่ระบบ',
      '注册': 'สมัครสมาชิก',
      '密码': 'รหัสผ่าน',
      '邮箱': 'อีเมล',
      '设置': 'ตั้งค่า',
      '退出': 'ออกจากระบบ',
      '确认': 'ยืนยัน',
      '取消': 'ยกเลิก',
      '保存': 'บันทึก',
      '删除': 'ลบ',
      '编辑': 'แก้ไข',
      '提交': 'ส่ง',
      '返回': 'ย้อนกลับ',
      '下一步': 'ถัดไป',
      '上一步': 'ก่อนหน้า',
    },
    'vn': {
      '欢迎': 'Chào mừng',
      '欢迎来到': 'Chào mừng bạn đến với',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Quản lý đầu tư của bạn một cách dễ dàng',
      '开始使用': 'Bắt đầu',
      '为什么选择我们': 'Tại sao chọn chúng tôi',
      '实时更新': 'Cập nhật thời gian thực',
      '首页': 'Trang chủ',
      '关于我们': 'Về chúng tôi',
      '联系我们': 'Liên hệ',
      '搜索...': 'Tìm kiếm...',
      '个人中心': 'Hồ sơ',
      '安全平台': 'Nền tảng an toàn',
      '登录': 'Đăng nhập',
      '注册': 'Đăng ký',
      '密码': 'Mật khẩu',
      '邮箱': 'Email',
      '设置': 'Cài đặt',
      '退出': 'Đăng xuất',
      '确认': 'Xác nhận',
      '取消': 'Hủy',
      '保存': 'Lưu',
      '删除': 'Xóa',
      '编辑': 'Chỉnh sửa',
      '提交': 'Gửi',
      '返回': 'Quay lại',
      '下一步': 'Tiếp theo',
      '上一步': 'Trước',
    },
    'id': {
      '欢迎': 'Selamat datang',
      '欢迎来到': 'Selamat datang di',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Kelola investasi Anda dengan mudah',
      '开始使用': 'Mulai',
      '为什么选择我们': 'Mengapa memilih kami',
      '实时更新': 'Pembaruan waktu nyata',
      '首页': 'Beranda',
      '关于我们': 'Tentang kami',
      '联系我们': 'Hubungi kami',
      '搜索...': 'Cari...',
      '个人中心': 'Profil',
      '安全平台': 'Platform aman',
      '登录': 'Masuk',
      '注册': 'Daftar',
      '密码': 'Kata sandi',
      '邮箱': 'Email',
      '设置': 'Pengaturan',
      '退出': 'Keluar',
      '确认': 'Konfirmasi',
      '取消': 'Batal',
      '保存': 'Simpan',
      '删除': 'Hapus',
      '编辑': 'Edit',
      '提交': 'Kirim',
      '返回': 'Kembali',
      '下一步': 'Selanjutnya',
      '上一步': 'Sebelumnya',
    },
    'my': {
      '欢迎': 'Selamat datang',
      '欢迎来到': 'Selamat datang di',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Urus pelaburan anda dengan mudah',
      '开始使用': 'Mula',
      '为什么选择我们': 'Mengapa pilih kami',
      '实时更新': 'Kemas kini masa nyata',
      '首页': 'Laman utama',
      '关于我们': 'Tentang kami',
      '联系我们': 'Hubungi kami',
      '搜索...': 'Cari...',
      '个人中心': 'Profil',
      '安全平台': 'Platform selamat',
      '登录': 'Log masuk',
      '注册': 'Daftar',
      '密码': 'Kata laluan',
      '邮箱': 'Emel',
      '设置': 'Tetapan',
      '退出': 'Log keluar',
      '确认': 'Sahkan',
      '取消': 'Batal',
      '保存': 'Simpan',
      '删除': 'Padam',
      '编辑': 'Edit',
      '提交': 'Hantar',
      '返回': 'Kembali',
      '下一步': 'Seterusnya',
      '上一步': 'Sebelumnya',
    },
    'ar': {
      '欢迎': 'مرحباً',
      '欢迎来到': 'مرحباً بك في',
      'IB 门户': 'بوابة IB',
      '轻松管理您的投资': 'إدارة استثماراتك بسهولة',
      '开始使用': 'ابدأ',
      '为什么选择我们': 'لماذا تختارنا',
      '实时更新': 'تحديثات فورية',
      '首页': 'الرئيسية',
      '关于我们': 'من نحن',
      '联系我们': 'اتصل بنا',
      '搜索...': 'بحث...',
      '个人中心': 'الملف الشخصي',
      '安全平台': 'منصة آمنة',
      '登录': 'تسجيل الدخول',
      '注册': 'تسجيل',
      '密码': 'كلمة المرور',
      '邮箱': 'البريد الإلكتروني',
      '设置': 'الإعدادات',
      '退出': 'تسجيل الخروج',
      '确认': 'تأكيد',
      '取消': 'إلغاء',
      '保存': 'حفظ',
      '删除': 'حذف',
      '编辑': 'تعديل',
      '提交': 'إرسال',
      '返回': 'رجوع',
      '下一步': 'التالي',
      '上一步': 'السابق',
    },
    'fa': {
      '欢迎': 'خوش آمدید',
      '欢迎来到': 'خوش آمدید به',
      'IB 门户': 'پورتال IB',
      '轻松管理您的投资': 'سرمایه‌گذاری‌های خود را به راحتی مدیریت کنید',
      '开始使用': 'شروع کنید',
      '为什么选择我们': 'چرا ما را انتخاب کنید',
      '实时更新': 'به‌روزرسانی‌های بی‌درنگ',
      '首页': 'صفحه اصلی',
      '关于我们': 'درباره ما',
      '联系我们': 'تماس با ما',
      '搜索...': 'جستجو...',
      '个人中心': 'پروفایل',
      '安全平台': 'پلتفرم امن',
      '登录': 'ورود',
      '注册': 'ثبت نام',
      '密码': 'رمز عبور',
      '邮箱': 'ایمیل',
      '设置': 'تنظیمات',
      '退出': 'خروج',
      '确认': 'تأیید',
      '取消': 'لغو',
      '保存': 'ذخیره',
      '删除': 'حذف',
      '编辑': 'ویرایش',
      '提交': 'ارسال',
      '返回': 'بازگشت',
      '下一步': 'بعدی',
      '上一步': 'قبلی',
    },
    'hi': {
      '欢迎': 'स्वागत है',
      '欢迎来到': 'में आपका स्वागत है',
      'IB 门户': 'IB पोर्टल',
      '轻松管理您的投资': 'अपने निवेश को आसानी से प्रबंधित करें',
      '开始使用': 'शुरू करें',
      '为什么选择我们': 'हमें क्यों चुनें',
      '实时更新': 'रीयल-टाइम अपडेट',
      '首页': 'होम',
      '关于我们': 'हमारे बारे में',
      '联系我们': 'संपर्क करें',
      '搜索...': 'खोजें...',
      '个人中心': 'प्रोफाइल',
      '安全平台': 'सुरक्षित प्लेटफॉर्म',
      '登录': 'लॉगिन',
      '注册': 'रजिस्टर',
      '密码': 'पासवर्ड',
      '邮箱': 'ईमेल',
      '设置': 'सेटिंग्स',
      '退出': 'लॉगआउट',
      '确认': 'पुष्टि करें',
      '取消': 'रद्द करें',
      '保存': 'सहेजें',
      '删除': 'हटाएं',
      '编辑': 'संपादित करें',
      '提交': 'सबमिट करें',
      '返回': 'वापस',
      '下一步': 'अगला',
      '上一步': 'पिछला',
    },
    'it': {
      '欢迎': 'Benvenuto',
      '欢迎来到': 'Benvenuto su',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Gestisci i tuoi investimenti facilmente',
      '开始使用': 'Inizia',
      '为什么选择我们': 'Perché scegliere noi',
      '实时更新': 'Aggiornamenti in tempo reale',
      '首页': 'Home',
      '关于我们': 'Chi siamo',
      '联系我们': 'Contattaci',
      '搜索...': 'Cerca...',
      '个人中心': 'Profilo',
      '安全平台': 'Piattaforma sicura',
      '登录': 'Accedi',
      '注册': 'Registrati',
      '密码': 'Password',
      '邮箱': 'Email',
      '设置': 'Impostazioni',
      '退出': 'Esci',
      '确认': 'Conferma',
      '取消': 'Annulla',
      '保存': 'Salva',
      '删除': 'Elimina',
      '编辑': 'Modifica',
      '提交': 'Invia',
      '返回': 'Indietro',
      '下一步': 'Successivo',
      '上一步': 'Precedente',
    },
    'nl': {
      '欢迎': 'Welkom',
      '欢迎来到': 'Welkom bij',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Beheer uw beleggingen gemakkelijk',
      '开始使用': 'Beginnen',
      '为什么选择我们': 'Waarom ons kiezen',
      '实时更新': 'Real-time updates',
      '首页': 'Startpagina',
      '关于我们': 'Over ons',
      '联系我们': 'Neem contact op',
      '搜索...': 'Zoeken...',
      '个人中心': 'Profiel',
      '安全平台': 'Veilig platform',
      '登录': 'Inloggen',
      '注册': 'Registreren',
      '密码': 'Wachtwoord',
      '邮箱': 'E-mail',
      '设置': 'Instellingen',
      '退出': 'Uitloggen',
      '确认': 'Bevestigen',
      '取消': 'Annuleren',
      '保存': 'Opslaan',
      '删除': 'Verwijderen',
      '编辑': 'Bewerken',
      '提交': 'Verzenden',
      '返回': 'Terug',
      '下一步': 'Volgende',
      '上一步': 'Vorige',
    },
    'pl': {
      '欢迎': 'Witamy',
      '欢迎来到': 'Witamy w',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Łatwo zarządzaj swoimi inwestycjami',
      '开始使用': 'Zacznij',
      '为什么选择我们': 'Dlaczego my',
      '实时更新': 'Aktualizacje w czasie rzeczywistym',
      '首页': 'Strona główna',
      '关于我们': 'O nas',
      '联系我们': 'Skontaktuj się',
      '搜索...': 'Szukaj...',
      '个人中心': 'Profil',
      '安全平台': 'Bezpieczna platforma',
      '登录': 'Zaloguj się',
      '注册': 'Zarejestruj się',
      '密码': 'Hasło',
      '邮箱': 'E-mail',
      '设置': 'Ustawienia',
      '退出': 'Wyloguj się',
      '确认': 'Potwierdź',
      '取消': 'Anuluj',
      '保存': 'Zapisz',
      '删除': 'Usuń',
      '编辑': 'Edytuj',
      '提交': 'Wyślij',
      '返回': 'Wróć',
      '下一步': 'Dalej',
      '上一步': 'Wstecz',
    },
    'tr': {
      '欢迎': 'Hoş geldiniz',
      '欢迎来到': 'Hoş geldiniz',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Yatırımlarınızı kolayca yönetin',
      '开始使用': 'Başla',
      '为什么选择我们': 'Neden bizi seçmelisiniz',
      '实时更新': 'Gerçek zamanlı güncellemeler',
      '首页': 'Ana sayfa',
      '关于我们': 'Hakkımızda',
      '联系我们': 'İletişim',
      '搜索...': 'Ara...',
      '个人中心': 'Profil',
      '安全平台': 'Güvenli platform',
      '登录': 'Giriş yap',
      '注册': 'Kayıt ol',
      '密码': 'Şifre',
      '邮箱': 'E-posta',
      '设置': 'Ayarlar',
      '退出': 'Çıkış yap',
      '确认': 'Onayla',
      '取消': 'İptal',
      '保存': 'Kaydet',
      '删除': 'Sil',
      '编辑': 'Düzenle',
      '提交': 'Gönder',
      '返回': 'Geri',
      '下一步': 'Sonraki',
      '上一步': 'Önceki',
    },
    'kk': {
      '欢迎': 'Қош келдіңіз',
      '欢迎来到': 'Қош келдіңіз',
      'IB 门户': 'IB Порталы',
      '轻松管理您的投资': 'Инвестицияларыңызды оңай басқарыңыз',
      '开始使用': 'Бастау',
      '为什么选择我们': 'Неліктен бізді таңдайсыз',
      '实时更新': 'Нақты уақытта жаңартулар',
      '首页': 'Басты бет',
      '关于我们': 'Біз туралы',
      '联系我们': 'Байланысу',
      '搜索...': 'Іздеу...',
      '个人中心': 'Профиль',
      '安全平台': 'Қауіпсіз платформа',
      '登录': 'Кіру',
      '注册': 'Тіркелу',
      '密码': 'Пароль',
      '邮箱': 'Электрондық пошта',
      '设置': 'Параметрлер',
      '退出': 'Шығу',
      '确认': 'Растау',
      '取消': 'Болдырмау',
      '保存': 'Сақтау',
      '删除': 'Өшіру',
      '编辑': 'Өңдеу',
      '提交': 'Жіберу',
      '返回': 'Артқа',
      '下一步': 'Келесі',
      '上一步': 'Алдыңғы',
    },
    'km': {
      '欢迎': 'ស្វាគមន៍',
      '欢迎来到': 'សូមស្វាគមន៍មកកាន់',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'គ្រប់គ្រងការវិនិយោគរបស់អ្នកបានងាយស្រួល',
      '开始使用': 'ចាប់ផ្តើម',
      '为什么选择我们': 'ហេតុអ្វីជ្រើសរើសយើង',
      '实时更新': 'ធ្វើបច្ចុប្បន្នភាពពេលវេលាជាក់ស្តែង',
      '首页': 'ទំព័រដើម',
      '关于我们': 'អំពីយើង',
      '联系我们': 'ទំនាក់ទំនងមកពួកយើង',
      '搜索...': 'ស្វែងរក...',
      '个人中心': 'ព័ត៌មានផ្ទាល់ខ្លួន',
      '安全平台': 'វេទិកាសុវត្ថិភាព',
      '登录': 'ចូល',
      '注册': 'ចុះឈ្មោះ',
      '密码': 'ពាក្យសម្ងាត់',
      '邮箱': 'អ៊ីមែល',
      '设置': 'ការកំណត់',
      '退出': 'ចាកចេញ',
      '确认': 'បញ្ជាក់',
      '取消': 'បោះបង់',
      '保存': 'រក្សាទុក',
      '删除': 'លុប',
      '编辑': 'កែសម្រួល',
      '提交': 'ដាក់ស្នើ',
      '返回': 'ត្រឡប់',
      '下一步': 'បន្ទាប់',
      '上一步': 'ថយក្រោយ',
    },
    'mn': {
      '欢迎': 'Тавтай морилно уу',
      '欢迎来到': 'Тавтай морилно уу',
      'IB 门户': 'IB Портал',
      '轻松管理您的投资': 'Хөрөнгөө хялбар зохицуулна уу',
      '开始使用': 'Эхлэх',
      '为什么选择我们': 'Яагаад биднийг сонгох вэ',
      '实时更新': 'Чин жагсаалт өөрчлөлт',
      '首页': 'Нүүр хуудас',
      '关于我们': 'Бидний тухай',
      '联系我们': 'Холбогдох',
      '搜索...': 'Хайх...',
      '个人中心': 'Профайл',
      '安全平台': 'Аюулгүй платформ',
      '登录': 'Нэвтрэх',
      '注册': 'Бүртгүүлэх',
      '密码': 'Нууц үг',
      '邮箱': 'И-мэйл',
      '设置': 'Тохиргоо',
      '退出': 'Гарах',
      '确认': 'Батлах',
      '取消': 'Цуцлах',
      '保存': 'Хадгалах',
      '删除': 'Устгах',
      '编辑': 'Засварлах',
      '提交': 'Илгээх',
      '返回': 'Буцах',
      '下一步': 'Дараагийн',
      '上一步': 'Өмнөх',
    },
    'tl': {
      '欢迎': 'Maligayang pagdating',
      '欢迎来到': 'Maligayang pagdating sa',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Pamahalaan ang iyong mga puhunan nang madali',
      '开始使用': 'Magsimula',
      '为什么选择我们': 'Bakit piliin kami',
      '实时更新': 'Mga update sa real-time',
      '首页': 'Home',
      '关于我们': 'Tungkol sa amin',
      '联系我们': 'Makipag-ugnayan',
      '搜索...': 'Maghanap...',
      '个人中心': 'Profile',
      '安全平台': 'Ligtas na platform',
      '登录': 'Mag-login',
      '注册': 'Magparehistro',
      '密码': 'Password',
      '邮箱': 'Email',
      '设置': 'Mga setting',
      '退出': 'Mag-logout',
      '确认': 'Kumpirmahin',
      '取消': 'Kanselahin',
      '保存': 'I-save',
      '删除': 'Burahin',
      '编辑': 'I-edit',
      '提交': 'Isumite',
      '返回': 'Bumalik',
      '下一步': 'Susunod',
      '上一步': 'Nakaraan',
    },
    'uz': {
      '欢迎': 'Xush kelibsiz',
      '欢迎来到': 'Xush kelibsiz',
      'IB 门户': 'IB Portal',
      '轻松管理您的投资': 'Investitsiyalaringizni oson boshqaring',
      '开始使用': 'Boshlash',
      '为什么选择我们': 'Nega bizni tanlaysiz',
      '实时更新': 'Haqiqiy vaqt yangilanishlari',
      '首页': 'Bosh sahifa',
      '关于我们': 'Biz haqimizda',
      '联系我们': 'Aloqa',
      '搜索...': 'Qidirish...',
      '个人中心': 'Profil',
      '安全平台': 'Xavfsiz platforma',
      '登录': 'Kirish',
      '注册': 'Roʻyxatdan oʻtish',
      '密码': 'Parol',
      '邮箱': 'Elektron pochta',
      '设置': 'Sozlamalar',
      '退出': 'Chiqish',
      '确认': 'Tasdiqlash',
      '取消': 'Bekor qilish',
      '保存': 'Saqlash',
      '删除': 'Oʻchirish',
      '编辑': 'Tahrirlash',
      '提交': 'Yuborish',
      '返回': 'Orqaga',
      '下一步': 'Keyingi',
      '上一步': 'Oldingi',
    },
  };

  const langMock = mockTranslations[targetLang] || {};
  return langMock[text] || text;
}

export function mockTranslate(texts: string[], targetLang: string): Record<string, string> {
  console.log('[mockTranslate] 被调用, 目标语言:', targetLang, '文本数:', texts.length);
  
  const results: Record<string, string> = {};
  texts.forEach((text) => {
    results[text] = mockTranslateSingle(text, targetLang);
  });
  
  console.log('[mockTranslate] 翻译结果:', results);
  return results;
}

export async function translateWithAPI(texts: string[], targetLang: string, sourceLang = 'en'): Promise<Record<string, string>> {
  return await translateBatchWithAPI(texts, targetLang, sourceLang);
}
